### ISSUE TITLE
Badge Hexagon Frame disappears after second time image drop

### ISSUE THREAD

**Issue by robarto** [myBadges-org/badgr-ui#24]
While creating a new badge you can drop an image and the hexagonal frame is created autoamtically.
If you drop an image a second time (for changing it) the frame disappears. 
If selecting the "change image" URL and goiing through the file manager menu, it works!

**Comment by PaulaScharf** [comment]
fixed with [971f48214674889648cd38a175f749ad47ef7c9a](https://github.com/myBadges-org/badgr-ui/commit/971f48214674889648cd38a175f749ad47ef7c9a)
