### ISSUE TITLE
PDF Export Design does not show criteria properly

### ISSUE THREAD

**Issue by robarto** [myBadges-org/badgr-ui#33]
[LASER World of Photonics - Open Photonik Pro Messestand (2).pdf](https://github.com/myBadges-org/badgr-ui/files/10802787/LASER.World.of.Photonics.-.Open.Photonik.Pro.Messestand.2.pdf)

shows only 
"..." and 
"Du h..." 

I don't know what the "..." should be, maybe the description "Du hast auf der Messe "LASER World of Photonics 2022" den Messestand der Fördermaßnahme "Open Photonik Pro" des Bundesministeriums für Bildung und Forschung (BMBF) besucht und alle Projekte kennengelernt, bei denen neue Formen der Zusammenarbeit von Wissenschaft und Wirtschaft mit der Maker- und Gründerszene ermöglicht werden."

but the criteria should be listed completely.

**Comment by umut0** [comment]
This is not possible unless we restrict the Title and Description to certain amount of Characters. 
Maybe we remove the description from the PDF and only add title completly?

![Screenshot from 2023-02-23 15-25-15](https://user-images.githubusercontent.com/2675557/220935075-3ea09fb0-7371-4918-af7c-e46659f74ad0.png)
